### Assignment 1: Security Monitoring Test Suite
### This file helps generate test data for KQL analysis and Azure Alert testing

### Environment Variables
@baseUrl = https://cst8919-du000086.azurewebsites.net
@localUrl = http://localhost:3000

### Test home page access
GET {{baseUrl}}/
Accept: text/html

###

### Test health check endpoint
GET {{baseUrl}}/health
Accept: application/json

###

### Test login initiation
GET {{baseUrl}}/login
Accept: text/html

###

### Test protected route access (without authentication - should redirect)
GET {{baseUrl}}/protected
Accept: text/html
